### ISSUE TITLE
How does the app know what technologies companies use?

### ISSUE THREAD

**Issue by connor11528** [MisconstruedRhinoceros/weirdRhino#307]
Hey I was looking through the server side code and trying to figure this out. On the deployed site is it listing out the actual technologies that companies are using or is it random? 

Perhaps to get legit data it could scrape something like [stackshare](https://stackshare.io/)? Very cool site and I like the idea!

**Comment by sara-gudeman** [comment]
Hey! So this is a very old and unmaintained project. But yes, the deployed site actually does list out technologies that the companies are using. We used a package called wappalyzer. You can see it in package.json. Thanks for checking the project out!

**Comment by connor11528** [comment]
Very cool! Thanks for the heads up will check it out
